kvblog/blogapp/urls.py
from django.urls import path
from blogapp import views


app_name = 'blogapp'

urlpatterns = [
    path('', views.main_view, name='index'),
    path('history/', views.history, name='history'),
    path('result/<int:id>/', views.create_result, name='result'),
    path('form/', views.create_form, name='form'),
    path('contacts/', views.create_contacts, name='contacts'),
    path('req_list/', views.Hh_RequestListView.as_view(), name='req_list'),
    path('req_detail/<int:pk>/', views.Hh_RequestDetailView.as_view(), name='req_detail'),
    path('req_create/', views.Hh_RequestCreateView.as_view(), name='req_create'),
    path('req_update/<int:pk>/', views.Hh_RequestUpdateView.as_view(), name='req_update'),
    path('req_delete/<int:pk>/', views.Hh_RequestDeleteView.as_view(), name='req_delete'),
]

kvblog/kvblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogapp.urls', namespace='blog')),
    path('users/', include('usersapp.urls', namespace='users'))
]

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kvblog/blogapp/models.py
from django.db import models
from usersapp.models import BlogUser

# Create your models here.
class TimeStamp(models.Model):
    """
    Abstract - для нее не создаются новые таблицы
    данные хранятся в каждом наследнике
    """
    create = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

class Hh_Request(TimeStamp):
    keywords = models.TextField(blank=False)
    # user = models.ForeignKey(BlogUser, on_delete=models.CASCADE)
    user = models.ForeignKey(BlogUser, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.keywords

class Hh_Response(models.Model):
    request = models.ForeignKey(Hh_Request, on_delete=models.CASCADE)
    skill_name = models.TextField(blank=False)
    skill_count = models.PositiveIntegerField (blank=False)
    skill_persent = models.PositiveIntegerField (blank=False)

    def __str__(self):
        return f'{self.request} {self.skill_name} {self.skill_count} {self.skill_persent}%'

kvblog/blogapp/forms.py
from django import forms

class Hh_Search_Form(forms.Form):
    hh_query = forms.CharField(label='строка поиска',
                               widget=forms.TextInput(attrs={'placeholder': 'Ключевые слова',
                                                             'class': 'form-control'}))

    OPTIONS_LIST = [
        ('all', 'Везде'),
        ('company', 'В названии компании'),
        ('name', 'В названии вакансии'),
    ]
    hh_option = forms.CharField(label='Где искать?',
                                widget=forms.Select(choices=OPTIONS_LIST,
                                attrs={'class': 'btn btn-secondary dropdown-toggle'}))

kvblog/blogapp/views.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from blogapp.models import Hh_Response, Hh_Request
from blogapp.forms import Hh_Search_Form
from django.urls import reverse, reverse_lazy
from django.views.generic.base import ContextMixin
import hhru.all_data as ad
import pprint


# Create your views here.
def main_view(request):
    requests = Hh_Request.objects.all()
    return render(request, 'blogapp/index.html', context={'requests': requests})

def history(request):
    # обратная сортировка
    requests = Hh_Request.objects.order_by('id').reverse()
    responses = Hh_Response.objects.all()
    return render(request, 'blogapp/history.html', context={'requests': requests, 'responses': responses})


def create_result(request, id):
    # hh_request = Hh_Request.objects.last()
    hh_request = get_object_or_404(Hh_Request, id=id)
    responses = Hh_Response.objects.filter(request = hh_request)
    return render(request, 'blogapp/result.html', context={'hh_request': hh_request, 'responses': responses})

def create_form(request):
    form = Hh_Search_Form(request.POST)
    if form.is_valid():
        # Получить данные из фомры
        hh_query = form.cleaned_data['hh_query']
        hh_option = form.cleaned_data['hh_option']
        # print(type(hh_option), f' hh_option = {hh_option}')
        # обработка полученных данных
        # print(type(hh_query),f' hh_query = {hh_query}')

        if hh_option == 'all':
            keywords_s = f'{hh_query}'
        elif hh_option == 'company':
            keywords_s = f'COMPANY_NAME:({hh_query})'
        elif hh_option == 'name':
            keywords_s = f'NAME:({hh_query})'

        ad.set_keywords(keywords_s)
        result = ad.get_data(keywords_s)
        # print(type(result))
        # print(type(result[0]['requirements']))
        # pprint.pprint(result)
        keywords = result[0]['keywords']
        # print(f'keywords={keywords}')
        current_user = request.user
        # print(type(current_user),f'current_user={current_user}')
        Hh_Request.objects.create(keywords = keywords, user = current_user)
        last_request = Hh_Request.objects.last()
        # print(f'last_request.id = {last_request.id}')

        requirements_l = result[0]['requirements']
        # print(type(requirements_l), f'requirements_l={requirements_l}')
        for item in requirements_l:
            # print(f'item={item}')
            # print(f'{item["name"]} {item["count"]} {round(int(item["persent"]))}')
            Hh_Response.objects.create(request=last_request,
                                       skill_name=item["name"],
                                       skill_count=item["count"],
                                       skill_persent=round(int(item["persent"])))
        #  подготовка для отображения на странице result.html
        hh_request = get_object_or_404(Hh_Request, id=last_request.id)
        responses = Hh_Response.objects.filter(request=hh_request)
        return render(request, 'blogapp/result.html', context={'hh_request': hh_request, 'responses': responses})
    else:
        return render(request, 'blogapp/form.html', context={'form': form})

    return render(request, 'blogapp/form.html', context={'form':form})


def create_contacts(request):
    dev_name = 'Konstantin Voloshenko'
    creation_date = 'Июнь 2022'
    return render(request, 'blogapp/contacts.html', context={'dev_name': dev_name, 'creation_date': creation_date})

# CRUD CREATE, READ (LIST, DETAIL), UPDATE, DELETE
# Read List: Список запросов
# Важно LoginRequiredMixin - он должен идти 1-ым
class Hh_RequestListView(LoginRequiredMixin, ListView):
    model = Hh_Request
    template_name = 'blogapp/req_list.html'

    def test_func(self):
        # return self.request.user.is_superuser
        return self.request.user.is_dbAdmin

    def get_queryset(self):
        user = self.request.user
        """
        Получение данных
        :return:
        """
        # print(f'self.test_func()={self.test_func()}')
        # return Hh_Request.objects.all()
        return Hh_Request.objects.order_by('id').reverse()


class ResponsesContextMixin(ContextMixin):
    def get_context_data(self, *args, **kwargs):
        """
        Отвечает за передачу параметров в контекст
        :param args:
        :param kwargs:
        :return:
        """
        hh_request = kwargs['object']
        responses = Hh_Response.objects.filter(request=hh_request)
        context = super().get_context_data(*args, **kwargs)
        context['responses'] = responses
        return context

# Read Detail
class Hh_RequestDetailView(UserPassesTestMixin, DetailView, ResponsesContextMixin):
    model = Hh_Request
    template_name = 'blogapp/req_detail.html'
    def test_func(self):
        # return self.request.user.is_superuser
        return self.request.user.is_dbAdmin

# Create
class  Hh_RequestCreateView(UserPassesTestMixin, CreateView):
    fields = '__all__'
    model = Hh_Request
    success_url = reverse_lazy('blog:req_list')
    template_name = 'blogapp/req_create.html'
    def test_func(self):
        # return self.request.user.is_superuser
        return self.request.user.is_dbAdmin
# Update
class Hh_RequestUpdateView(UserPassesTestMixin, UpdateView, ResponsesContextMixin):
    fields = '__all__'
    model = Hh_Request
    success_url = reverse_lazy('blog:req_list')
    template_name = 'blogapp/req_update.html'
    def test_func(self):
        # return self.request.user.is_superuser
        return self.request.user.is_dbAdmin

# Delete
class Hh_RequestDeleteView(UserPassesTestMixin, DeleteView):
    fields = '__all__'
    model = Hh_Request
    success_url = reverse_lazy('blog:req_list')
    template_name = 'blogapp/req_delete.html'
    def test_func(self):
        # return self.request.user.is_superuser
        return self.request.user.is_dbAdmin

kvblog/blogapp/templates/blogapp/contacts.html
{% extends "base.html" %}
{% load static %}

{% block title%}Контакты{% endblock %}

{% block content %}
<h1>
    Контакты
</h1>
<h2>
    Разработчик: {{dev_name}}
</h2>
<h3>
    дата создания: {{creation_date}}
</h3>
<!--    img - картинка-->
<div class="media">
        <img src="{% static 'images/IMG_1616.JPG' %}" width="200px" class="mr-3">
</div>
{% endblock %}

<div class="alert alert-success" role="alert">
<p>
    {% block jok%}Опытный разработчик всегда посмотрит направо и налево, даже если переходит улицу с односторонним движением {% endblock %}
</p>
</div>

kvblog/blogapp/templates/blogapp/form.html
{% extends "base.html" %}

{% block title%}Поиск{% endblock %}

{% block content %}
    <h1>Форма для поиска</h1>
    <!--    form для отправки данных на сервер-->
    <div class="input-group mb-3">
<!--    <form action="results.html" method="post">-->
<!--&lt;!&ndash;        input - поля для ввода данных или кнопки&ndash;&gt;-->
<!--&lt;!&ndash;        type - тип поля, value-его значение, placeholder-подсказка&ndash;&gt;-->
<!--        <input type="text" name="query_string" value="" placeholder="строка поиска" class="form-control">-->
<!--        <br>-->
<!--        <br>-->
<!--&lt;!&ndash;        submit - кнопка&ndash;&gt;-->
<!--&lt;!&ndash;        select - выпадающий список&ndash;&gt;-->
<!--        <p><select name="where" class="btn btn-secondary dropdown-toggle">-->
<!--                <option value="all">Везде</option>-->
<!--                <option value="company">В названии компании</option>-->
<!--                <option selected value="name">В названии вакансии</option>-->
<!--            </select>-->
<!--        <input type="submit" value="Искать вакансии" class="btn btn-secondary"></p>-->
<!--    </form>-->
        <form id="hhSearchForm" method="post">
            {% csrf_token %}
            {{ form }}
            <button type="submit" class="btn btn-secondary" id="hhSearchButton">Искать вакансии</button>
        </form>
    </div>
    <hr>
{% endblock %}

<div class="alert alert-success" role="alert">
<p>
    {% block jok%}Существует два вида языков программирования: одни – все ругают, другими не пользуются {% endblock %}
</p>
</div>

kvblog/blogapp/templates/blogapp/history.html
{% extends "base.html" %}

{% block title%}Результаты{% endblock %}

{% block content %}
    <h1>История запросов</h1>
    <h3>Ключевые слова:</h3>

 {% for request in requests %}
       <a class="nav-link" href="/result/{{ request.id }}/">{{ request.keywords }}  {{ request.id }}</a>
 {% endfor %}
<!--table - таблица, tr-строка, td-столбец, th-заголовок-->
<br><br>

{% endblock %}

<div class="alert alert-success" role="alert">
<p>
    {% block jok%}Пока компьютеры не умеют мыслить самостоятельно, им можно доверять{% endblock %}
</p>
</div>

kvblog/blogapp/templates/blogapp/index.html
{% extends "base.html" %}

{% block title%}Мегапарсер hh{% endblock %}

{% block content %}
<h1>
    Мегапарсер hh.ru
</h1>
<h2>
    Это главная страница
</h2>
<h3>Информация о системе</h3>

<p>Этот сайт выполняет запросы к hh.ru по API,
    получает вакансии по заданным критериям поиска,
    парсит ответ и анализирует необходимые навыки.</p>
<p>Можно задать различные параметры поиска</p>
{% endblock %}

<div class="alert alert-success" role="alert">
<p>
    {% block jok%}Если вы начинаете сгонять муху с монитора при помощи курсора мыши, пора выключать компьютер {% endblock %}
</p>
</div>

kvblog/blogapp/templates/blogapp/req_create.html
{% extends "base.html" %}

{% block title%}Список запросов{% endblock %}

{% block content %}
<h1>
    Создание запроса
</h1>
        <form id="hhSearchForm" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-secondary" id="hhSearchButton">Сохранить</button>
        </form>
        <div class="alert alert-warning" role="alert">
            <p>Внимание! Данные будут созданы только в БД. Запрос к HH.RU не будет отправляться!</p>
        </div>
{% endblock %}

<div class="alert alert-success" role="alert">
<p>
    {% block jok%}Функция будильника еще поспать ввела программиста утром в бесконечный цикл{% endblock %}
</p>
</div>

kvblog/blogapp/templates/blogapp/req_delete.html
{% extends "base.html" %}

{% block title%}Список запросов{% endblock %}

{% block content %}
<h1>
    Удаление запроса
</h1>
<div class="">
    <h2>{{object.keywords}}</h2>
    <h3>Вы уверены?</h3>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Удалить</button>
    </form>
</div>
{% endblock %}

<div class="alert alert-success" role="alert">
<p>
    {% block jok%}Функция будильника еще поспать ввела программиста утром в бесконечный цикл{% endblock %}
</p>
</div>

kvblog/blogapp/templates/blogapp/req_detail.html
{% extends "base.html" %}

{% block title%}Список запросов{% endblock %}

{% block content %}
<h1>
    Детали запроса
</h1>
    <table class="table table-striped table-dark">
        <tr>
            <th>id</th>
            <th>Ключевые слова</th>
            <th>Дата создания</th>
            <th>Дата изменения</th>
            <th>Пользователь</th>
        </tr>
        <tr>
            <td>{{object.id}}</td>
            <td>{{object.keywords}}</td>
            <td>{{object.create}}</td>
            <td>{{object.update}}</td>
            <td>{{object.user}}</td>
        </tr>
    </table>
            <a class="btn btn-secondary" href="{% url 'blog:req_update' pk=object.id %}">Изменить</a>
            /
            <a class="btn btn-secondary" href="{% url 'blog:req_delete' pk=object.id %}">Удалить</a>
<!--        <p><a class="nav-link" href="/result/{{ object.id }}/">Навыки</a></p>-->

<!--table - таблица, tr-строка, td-столбец, th-заголовок-->
<br>
<h3>Навыки</h3>
    <table class="table table-striped table-dark">
    <tr>
<!--        <th>id запроса</th>-->
        <th>Навык</th>
        <th>Количество</th>
        <th>%</th>
    </tr>
 {% for item in responses %}
        <tr>
<!--            <td>{{ item.request.id }}</td>-->
            <td>{{ item.skill_name }}</td>
            <td>{{ item.skill_count }}</td>
            <td>{{ item.skill_persent }}</td>
        </tr>
 {% endfor %}
    </table>

{% endblock %}

<div class="alert alert-success" role="alert">
<p>
    {% block jok%}Функция будильника еще поспать ввела программиста утром в бесконечный цикл{% endblock %}
</p>
</div>

kvblog/blogapp/templates/blogapp/req_list.html
{% extends "base.html" %}

{% block title%}Список запросов{% endblock %}

{% block content %}
<h1>
    Список запросов
</h1>
<a class="btn btn-secondary" href="{% url 'blog:req_create' %}">Создать новую запись в БД</a>
<br><br>
<ul>
    {% for item in object_list %}
        <li>
            <a class="btn btn-secondary" href="{% url 'blog:req_update' pk=item.pk %}">Изменить</a>
            /
            <a class="btn btn-secondary" href="{% url 'blog:req_delete' pk=item.pk %}">Удалить</a>
            {{item.id}}
            <a href="{% url 'blog:req_detail' pk=item.pk %}">{{item.keywords}}</a>
        </li>
    {% endfor %}

</ul>
{% endblock %}

<div class="alert alert-success" role="alert">
<p>
    {% block jok%}Функция будильника еще поспать ввела программиста утром в бесконечный цикл{% endblock %}
</p>
</div>

kvblog/blogapp/templates/blogapp/req_update.html
{% extends "base.html" %}

{% block title%}Список запросов{% endblock %}

{% block content %}
<h1>
    Изменение запроса
</h1>
        <form id="hhSearchForm" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-secondary" id="hhSearchButton">Сохранить</button>
            <div class="alert alert-warning" role="alert">
            <p>Внимание! Данные будут изменены только в БД. Запрос к HH.RU не будет отправляться!</p>
            </div>
        </form>

<!--table - таблица, tr-строка, td-столбец, th-заголовок-->
<br>
<h3>Навыки</h3>
    <table class="table table-striped table-dark">
    <tr>
<!--        <th>id запроса</th>-->
        <th>Навык</th>
        <th>Количество</th>
        <th>%</th>
    </tr>
 {% for item in responses %}
        <tr>
<!--            <td>{{ item.request.id }}</td>-->
            <td>{{ item.skill_name }}</td>
            <td>{{ item.skill_count }}</td>
            <td>{{ item.skill_persent }}</td>
        </tr>
 {% endfor %}
    </table>
{% endblock %}

<div class="alert alert-success" role="alert">
<p>
    {% block jok%}Функция будильника еще поспать ввела программиста утром в бесконечный цикл{% endblock %}
</p>
</div>

kvblog/blogapp/templates/blogapp/result.html
{% extends "base.html" %}

{% block title%}Результаты{% endblock %}

{% block content %}
    <h1>Результаты запроса</h1>
    <h3>Ключевые слова:</h3>
    <h5>{{ hh_request.keywords }}</h5>

<!--table - таблица, tr-строка, td-столбец, th-заголовок-->
<br>
<h3>Навыки</h3>
    <table class="table table-striped table-dark">
    <tr>
        <th>Навык</th>
        <th>Количество</th>
        <th>%</th>
    </tr>
 {% for item in responses %}
        <tr>
            <td>{{ item.skill_name }}</td>
            <td>{{ item.skill_count }}</td>
            <td>{{ item.skill_persent }}</td>
        </tr>
 {% endfor %}
    </table>
{% endblock %}

<div class="alert alert-success" role="alert">
<p>
    {% block jok%}Пока компьютеры не умеют мыслить самостоятельно, им можно доверять{% endblock %}
</p>
</div>