kvblog/blogapp/urls.py
from django.urls import path
from blogapp import views


app_name = 'blogapp'

urlpatterns = [
    path('', views.main_view, name='index'),
    path('history/', views.history, name='history'),
    path('result/<int:id>/', views.create_result, name='result'),
    path('form/', views.create_form, name='form'),
    path('contacts/', views.create_contacts, name='contacts'),
    path('req_list/', views.Hh_RequestListView.as_view(), name='req_list'),
    path('req_detail/<int:pk>/', views.Hh_RequestDetailView.as_view(), name='req_detail'),
    path('req_create/', views.Hh_RequestCreateView.as_view(), name='req_create'),
    path('req_update/<int:pk>/', views.Hh_RequestUpdateView.as_view(), name='req_update'),
    path('req_delete/<int:pk>/', views.Hh_RequestDeleteView.as_view(), name='req_delete'),
]

kvblog/kvblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogapp.urls', namespace='blog')),
    path('users/', include('usersapp.urls', namespace='users'))
]

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kvblog/usersapp/urls.py
from django.urls import path
from usersapp import views
from django.contrib.auth.views import LogoutView

app_name = 'usersapp'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.UserCreateView.as_view(), name='register')
]

kvblog/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <!--    подключение css-->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.css' %}" >
    <meta charset="UTF-8">
    <title>{% block title%}{% endblock %}</title>
</head>
<body class="p-3 mb-2 bg-light text-dark">
<div class="alert alert-success" role="alert">
<ul class="nav">
  <li class="nav-item">
    <a class="nav-link active" href="{% url 'blog:index' %}">На главную</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'blog:form' %}">Начать поиск</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'blog:history' %}">История</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'blog:req_list' %}">Управление данными</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'blog:contacts' %}">Контакты</a>
  </li>
    {% if user.is_authenticated %}
        <li class="nav-item">
                <div class="nav-link">Привет, {{user.username}}</div>
        </li>
        <li class="nav-item">
                <a class="nav-link" href="{% url 'users:logout' %}">Выход</a>
        </li>
    {% else %}
        <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:login' %}">Вход</a>
        </li>

        <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:register' %}">Регистрация</a>
        </li>
    {% endif %}

</ul>
</div>
<!-- Main Content -->
<div class="container">
    {% block content %}{% endblock %}
</div>


<div class="alert alert-success" role="alert">
<p>
    {% block jok%}Пока компьютеры не умеют мыслить самостоятельно, им можно доверять{% endblock %}
</p>
</div>

</body>
</html>